### PR TITLE
reworked GUI to make it compatible with quark

### PR DESCRIPTION
**Pull request by TimGoll**
As promiesed, here are the new GUIs. I changed them all in a way that they are compatible with quark. Furthermore there is now space inbetween the player inventory and the chest inventory for the word "Inventory". All borders have been changed to fit the vanilla style.

**Chest storage area:**
- copper: `9x5 = 45` (old: `45`)
- iron: `9x6 = 54` (old: `54`)
- silver: `13x6 = 78` (old: `72`)
- gold: `13x7 = 91` (old: `81`)
- diamond: `13x9 = 117` (old: `108`)

The hotbar is in a 3x3 grid on the left side for silver, gold and diamond chests. If you want to make it easier for the players, take a look at thaumcraft and the way it handles it.

**Thaumcraft:**
image
_(Source: https://youtu.be/pDQZRhQq584?t=9m19s; you can get the needed information from this scene)_

[ closing #32 ]

### CODE REVIEW

**Comment by TimGoll** [comment]
Okay! No problem. But please use a system like [Wearable Backpacks](https://minecraft.curseforge.com/projects/wearable-backpacks). This is texture pack friendy

**Comment by T145** [comment]
Hey! Customizable GUI sizing has been implemented, and I was wondering if you'd be up to resizing the base GUI image from 512x512 to 1.024x1,024, doubling it. I use a system similar to Wearable Backpacks, and use their GUI texture directly (by permission of course). Resizing would not just be plainly doubling the size, but positioning everything appropriately. Image is here: https://github.com/T145/metalchests/blob/master/src/main/resources/assets/metalchests/textures/gui/chest.png

**Comment by T145** [comment]
@TimGoll Hey! Customizable GUI sizing has been implemented, and I was wondering if you'd be up to resizing the base GUI image from 512x512 to 1.024x1,024, doubling it. I use a system similar to Wearable Backpacks, and use their GUI texture directly (by permission of course). Resizing would not just be plainly doubling the size, but positioning everything appropriately. Image is here: https://github.com/T145/metalchests/blob/master/src/main/resources/assets/metalchests/textures/gui/chest.png

**Comment by TimGoll** [comment]
yeah sure. but please explain. What is my job when you're already using their texture? :D

**Comment by T145** [comment]
To resize the texture, so that there are more rows & columns available. For increasing it a reasonable amount, I think you'd only have to double the height. So basically you'd have two of that lowest inventory smashed together & the top GUI texture it gets translated to doubled as well.

Btw, my Discord: https://discord.gg/3a3RW7H

**Pull request closed without merging**
